-- Handlers.add(
--     "test",
--     Handlers.utils.hasMatchingTag("Action", "Test"),
--     function(msg)
--         local test = "abc"
--         local write_res = sql_write([[INSERT INTO Users (Name) VALUES (?)]], test)
--         local p = sql_run([[SELECT * FROM Users Where Name = "abc" ]])
--         for _, pkg in ipairs(p) do
--             print(pkg)
--         end
--         print(tostring(p))
--     end
-- )
-- Handlers.add(
--     "Stake",
--     Handlers.utils.hasMatchingTag("Action", "Stake"),
--     function(msg)
--         -- CHECK USER TABLE, if not then add or send notif to register (?)
--         if not Users[msg.From] then Users[msg.Sender] = "0" end 
--         -- FE sends transfer message as below
--             -- ao.send(
--             --     Target = msg.Tags.bridgedID,
--             --     Action = "Transfer",
--             --     Recipient = platformID,
--             --     Quantity = msg.Tags.Quantity,
--             --     ["X-Action"] = "Staked"
--             -- )
--             -- THIS CREATES A MSG ID
--         -- log the info
--             -- TRANSACTIONS.ID = msg.Tags.msgID
--             -- TRANSACTIONS.amount= msg.Tags.Quantity, 
--             -- TRANSACTIONS.userID= msg.From, 
--             -- TRANSACTIONS.tokenID = msg.Tags.bridgedID, 
--             -- TRANSACTIONS.projectID = msg.["X-ProjectID"]
--             -- TRANSACTION.type = btf
--             -- TRANSACTION.status = pending --IMPORTANT ADD
--             -- store to project = X-ProjectID (?)
--     end
-- )
 

-- DUMMY SQL TABLE IDK
-- USER:
--     userID
-- --    transactions table (?)
-- PROJECT:
--     projectID
--     pTokenID
--     usersStaked
-- TRANSACTIONS:
--     {
--         time(?)
--         userID
--         tokenID
--         Quantity
--         projectID
--         status
--         enum type{
--             btf -- bridged to fa
--             atf -- ao to fa
--             ftp -- fa to proj
--             ptf -- proj to fa
--             ftu -- fa to user
--         }
--     }
-- BRIDGEDTOKENS: 
--     AOETH: id
--     AOSOL: id
-- TOTALS:
--     shall this be on the pid or bid (?)
--     projectID.bridgedID.Quantity

-- Handlers.add(
--     "Create-Transaction",
--     Handlers.utils.hasMatchingTag("Action", "Create-Transaction"),
--     function(msg)
-- -- maybe this needs to be just a functiona dn not a handler
--     end
-- )



-- Handlers.add(
--     "test",
--     Handlers.utils.hasMatchingTag("Action", "Test"),
--     function(msg)
--         print(verifiedBridgedToken)
--     end
-- )
