const project = {
    name:"",
    processID:"",
    tokenID:"",
    tokensHeld:[{
        id:"",
        ticker:"",
        quantity:""
    }, {
        id:"",
        ticker:"",
        quantity:""
    }],
    distribution:[{
        id:"",
        quantity:""
    }, {
        id:"",
        quantity:""
    }],
    tokenFlow:{
        daily:"",
        weekly:"",
        monthly:"",
    },
    messagesPerDay:"",
    uniqueUsers:{
        daily:"",
        weekly:"",
        monthly:"",
        lifetime:""
    },
    typesOfMessages:[{
        name:"",
        lastSixMonths:{
            jan:"",
            feb:"",
        }
    },]
}